name: Test Install Zig Action

on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        include:
          - type: latest
            version: 0.15.1
          - type: master
            version: master
          - type: empty
            version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Zig ${{ matrix.version }}
        uses: ./
        env:
          DEBUG: 1
        with:
          version: ${{ matrix.version }}
      - name: Check Zig version
        run: zig version
